name: Build Test and Deploy

on: 
   push:
      branches:
        -main
   pull_request:
      branches:
        -main

env:
   PROJECT_VERSION: 1.0.0

jobs:
   build:
      name: Build and Cache Dependencies
      runs-on: ubuntu-latest

      steps:
         - name: Checkout
           uses: actions/checkout@4.2.2
         - name: Setup Java JDK
           uses: actions/setup-java@4.5.0
           with:
              distribution: zulu
         - run: mvn clean pakage -DskipTests --name helloworld.jar
   
    
